<?php declare(strict_types=1);
/**
 * This file was generated by PhpFilePersistentCache. Please don't change it manually.
 *
 * some additional comment, you can add implementation details related with your project here
 * second line comment
 */
return [
    'GET'  => [
        '/handler-and-one-middleware' => [[\AP\Routing\Cache\Tests\PhpFilePersistentCacheTest::class, 'handler'], [\AP\Routing\Cache\Tests\PhpFilePersistentCacheTest::class, 'middleware']],
        '/one-handler'                => [[\AP\Routing\Cache\Tests\PhpFilePersistentCacheTest::class, 'handler']],
    ],
    'POST' => [
        '/one-handler' => [[\AP\Routing\Cache\Tests\PhpFilePersistentCacheTest::class, 'handler']],
    ],
];